"""initial schema

Revision ID: 0acadfc52c3e
Revises: 
Create Date: 2026-08-07 21:55:11.151888
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '0acadfc52c3e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_ts', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=200), nullable=True),
    sa.Column('actor_hash', sa.String(length=64), nullable=True),
    sa.Column('jti', sa.String(length=64), nullable=True),
    sa.Column('parent_jti', sa.String(length=64), nullable=True),
    sa.Column('root_jti', sa.String(length=64), nullable=True),
    sa.Column('scopes', sa.JSON(), nullable=True),
    sa.Column('denied_scopes', sa.JSON(), nullable=True),
    sa.Column('required_scope', sa.String(length=128), nullable=True),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('row_hash')
    )
    op.create_index('ix_audit_action_ts', 'audit_log', ['action', 'ts'], unique=False)
    op.create_index('ix_audit_actor_ts', 'audit_log', ['actor_id', 'ts'], unique=False)
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_log_decision'), 'audit_log', ['decision'], unique=False)
    op.create_index(op.f('ix_audit_log_jti'), 'audit_log', ['jti'], unique=False)
    op.create_index(op.f('ix_audit_log_parent_jti'), 'audit_log', ['parent_jti'], unique=False)
    op.create_index(op.f('ix_audit_log_root_jti'), 'audit_log', ['root_jti'], unique=False)
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('delegation_edge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_jti', sa.String(length=64), nullable=False),
    sa.Column('child_jti', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_jti', 'child_jti', name='uq_edge')
    )
    op.create_index(op.f('ix_delegation_edge_child_jti'), 'delegation_edge', ['child_jti'], unique=False)
    op.create_index(op.f('ix_delegation_edge_parent_jti'), 'delegation_edge', ['parent_jti'], unique=False)
    op.create_table('revocation',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('root_of_revocation', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_revocation_revoked_at'), 'revocation', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_revocation_root_of_revocation'), 'revocation', ['root_of_revocation'], unique=False)
    op.create_table('subject_map',
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('identifier_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('display_label', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('identifier_hash', 'kind', name='uq_subject_identifier')
    )
    op.create_index(op.f('ix_subject_map_identifier_hash'), 'subject_map', ['identifier_hash'], unique=False)
    op.create_table('token_record',
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('subject_id', sa.String(length=200), nullable=False),
    sa.Column('parent_jti', sa.String(length=64), nullable=True),
    sa.Column('root_jti', sa.String(length=64), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('delegation_chain', sa.JSON(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('jti')
    )
    op.create_index(op.f('ix_token_record_parent_jti'), 'token_record', ['parent_jti'], unique=False)
    op.create_index(op.f('ix_token_record_root_jti'), 'token_record', ['root_jti'], unique=False)
    op.create_index(op.f('ix_token_record_subject_id'), 'token_record', ['subject_id'], unique=False)
    op.create_table('pending_approval',
    sa.Column('approval_id', sa.String(length=64), nullable=False),
    sa.Column('parent_jti', sa.String(length=64), nullable=False),
    sa.Column('parent_subject_id', sa.String(length=200), nullable=False),
    sa.Column('child_agent_id', sa.String(length=200), nullable=False),
    sa.Column('child_subject_id', sa.String(length=200), nullable=False),
    sa.Column('requested_scopes', sa.JSON(), nullable=False),
    sa.Column('sensitive_scopes', sa.JSON(), nullable=False),
    sa.Column('ttl_seconds', sa.Integer(), nullable=False),
    sa.Column('parent_exp', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=200), nullable=True),
    sa.Column('child_jti', sa.String(length=64), nullable=True),
    sa.Column('child_token', sa.Text(), nullable=True),
    sa.Column('collected', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['child_jti'], ['token_record.jti'], ),
    sa.PrimaryKeyConstraint('approval_id')
    )
    op.create_index(op.f('ix_pending_approval_parent_jti'), 'pending_approval', ['parent_jti'], unique=False)
    op.create_index(op.f('ix_pending_approval_status'), 'pending_approval', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_approval_status'), table_name='pending_approval')
    op.drop_index(op.f('ix_pending_approval_parent_jti'), table_name='pending_approval')
    op.drop_table('pending_approval')
    op.drop_index(op.f('ix_token_record_subject_id'), table_name='token_record')
    op.drop_index(op.f('ix_token_record_root_jti'), table_name='token_record')
    op.drop_index(op.f('ix_token_record_parent_jti'), table_name='token_record')
    op.drop_table('token_record')
    op.drop_index(op.f('ix_subject_map_identifier_hash'), table_name='subject_map')
    op.drop_table('subject_map')
    op.drop_index(op.f('ix_revocation_root_of_revocation'), table_name='revocation')
    op.drop_index(op.f('ix_revocation_revoked_at'), table_name='revocation')
    op.drop_table('revocation')
    op.drop_index(op.f('ix_delegation_edge_parent_jti'), table_name='delegation_edge')
    op.drop_index(op.f('ix_delegation_edge_child_jti'), table_name='delegation_edge')
    op.drop_table('delegation_edge')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_root_jti'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_parent_jti'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_jti'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_decision'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_index('ix_audit_actor_ts', table_name='audit_log')
    op.drop_index('ix_audit_action_ts', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
